Couldn't get pip cache to work
flake8 was not found in `Lint with flake8`:
 Run # stop the build if there are Python syntax errors or undefined names
  # stop the build if there are Python syntax errors or undefined names
  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.6/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.6/x64/lib
 /home/runner/work/_temp/30ce31af-7ae8-4620-b450-553771ed0afe.sh: line 2: flake8: command not found
 Error: Process completed with exit code 127.

Change to caching using `env.pythonLocation` that I found from
[here](https://medium.com/ai2-blog/python-caching-in-github-actions-e9452698e98d)